const CARD_BODY_LABEL = {
  abatement: 'Abatement',
  age: 'Age',
  asserted: 'Asserted',
  claimType: 'Claim Type',
  class: 'Class',
  clinicalStatus: 'Clinical Status',
  concept: 'Concept',
  conditions: 'Conditions',
  coverage: 'Coverage',
  diagnosis: 'Diagnosis',
  diastolic: 'Diastolic',
  dosage: 'Dosage',
  ending: 'Ending',
  given: 'Given',
  measure: 'Measure',
  medication: 'Medication',
  medications: 'Medications',
  onset: 'Onset',
  orderedBy: 'Ordered By',
  period: 'Period',
  primarySource: 'Primary Source',
  provider: 'Provider',
  quantity: 'Quantity',
  reason: 'Reason',
  referral: 'Referral',
  refills: 'Refills',
  reported: 'Reported',
  result: 'Result',
  role: 'Role',
  startingOn: 'Starting On',
  status: 'Status',
  supply: 'Supply',
  systolic: 'Systolic',
  taken: 'Taken',
  total: 'Total',
  totalBenefit: 'Total Benefit',
  totalCost: 'Total Cost',
  type: 'Type',
  use: 'Use',
  vaccine: 'Vaccine',
  value: 'Value',
  valueRatio: 'Value Ratio',
  verification: 'Verification',
};

export default CARD_BODY_LABEL;
